import os
from datetime import datetime

os.makedirs("reports", exist_ok=True)


def export_weekly_markdown(articles: list[dict]) -> str:
    """Export weekly summarized articles to a Markdown file and return the path."""
    # localized import to prevent circularity
    from notifications.telegram import _emoji, _confidence_icon

    now = datetime.now().strftime("%Y-%m-%d")
    filename = f"reports/Weekly_Brief_{now}.md"
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# 📅 Weekly Intelligence Brief — {now}\n\n")
        
        verified = len([a for a in articles if a.get("confidence", 0) >= 80])
        f.write(f"**Total Articles Processing:** {len(articles)}\n")
        f.write(f"**Verified High-Signal:** {verified}\n\n")
        
        f.write("---\n\n")
        
        f.write("## 🏆 All Weekly Stories\n\n")
        top = sorted(articles, key=lambda a: a.get("confidence", 0), reverse=True)
        for a in top:
            conf = a.get("confidence", 0)
            icon = _confidence_icon(conf)
            cat = a.get("category", "General")
            cat_emoji = _emoji(cat)
            title = a.get("title", "")
            url = a.get("url", "")
            
            f.write(f"### {icon} {title}\n")
            f.write(f"**Category:** {cat_emoji} {cat} | **Confidence:** {conf}%\n\n")
            if a.get("reasoning"):
                f.write(f"> {a.get('reasoning')}\n\n")
            f.write(f"[Read Source]({url})\n\n")
            f.write("---\n\n")
            
        f.write("*Auto-generated by Daily News Agent*\n")
        
    return filename
